const demoData = [
    {
        "first": "Anna",
        "last": "Sienko",
        "mother": "",
        "father": "",
        "sex": "Female",
        "spouse": "Pawel Sienko",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Aniela",
        "last": "Sienko",
        "mother": "Anna Sienko",
        "father": "Pawel Sienko",
        "sex": "Female",
        "spouse": "Franciszek Wyskiel",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Jozefa",
        "last": "Sienko",
        "mother": "Aniela Sienko",
        "father": "Franciszek Wyskiel",
        "sex": "Female",
        "spouse": "Eugeniusz Plesniak",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Elzbieta",
        "last": "Plesniak",
        "mother": "Jozefa Sienko",
        "father": "Eugeniusz Plesniak",
        "sex": "Female",
        "spouse": "Leszek Wojciechowski",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Danusia",
        "last": "Plesniak",
        "mother": "Jozefa Sienko",
        "father": "Eugeniusz Plesniak",
        "sex": "Female",
        "spouse": "Andrzej Klimczak",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Zbigniew",
        "last": "Plesniak",
        "mother": "Jozefa Sienko",
        "father": "Eugeniusz Plesniak",
        "sex": "Male",
        "spouse": "Ewa",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Monica",
        "last": "Wojciechowski",
        "mother": "Elzbieta Plesniak",
        "father": "Leszek Wojciechowski",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Martin",
        "last": "Wojciechowski",
        "mother": "Elzbieta Plesniak",
        "father": "Leszek Wojciechowski",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Urszula",
        "last": "Plesniak",
        "mother": "Jozefa Sienko",
        "father": "Eugeniusz Plesniak",
        "sex": "Female",
        "spouse": "Robert Szucio",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Jozefa",
        "last": "Sienko",
        "mother": "Anna Sienko",
        "father": "Pawel Sienko",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Jan",
        "last": "Sienko",
        "mother": "Anna Sienko",
        "father": "Pawel Sienko",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Kazimierz",
        "last": "Sienko",
        "mother": "Anna Sienko",
        "father": "Pawel Sienko",
        "sex": "Male",
        "spouse": "Maria Wozniak",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": 1896,
        "deathYear": 1978
    },
    {
        "first": "Stefan",
        "last": "Kazimierowicz",
        "mother": "Maria Wozniak",
        "father": "Kazimierz Sienko",
        "sex": "Male",
        "spouse": "Urszula Przygoda",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": 1923,
        "deathYear": ""
    },
    {
        "first": "Stanislaw",
        "last": "Sienko",
        "mother": "Maria Wozniak",
        "father": "Kazimierz Sienko",
        "sex": "Male",
        "spouse": "Zofia Siegoni",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": 1930,
        "deathYear": 2009
    },
    {
        "first": "Ewa",
        "last": "Kazimierowicz",
        "mother": "Urszula Przygoda",
        "father": "Stefan Kazimierowicz",
        "sex": "Female",
        "spouse": "Roman Falinski",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": 1949,
        "deathYear": 2017
    },
    {
        "first": "Mariusz",
        "last": "Kazimierowicz",
        "mother": "Urszula Przygoda",
        "father": "Stefan Kazimierowicz",
        "sex": "Male",
        "spouse": "Barbara",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": 1953,
        "deathYear": ""
    },
    {
        "first": "Rafal",
        "last": "Falinski",
        "mother": "Ewa Kazimierowicz",
        "father": "Roman Falinski",
        "sex": "Male",
        "spouse": "Ala Pecha",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Sebastian",
        "last": "Falinski",
        "mother": "Ewa Kazimierowicz",
        "father": "Roman Falinski",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Lukasz",
        "last": "Falinski",
        "mother": "Ewa Kazimierowicz",
        "father": "Roman Falinski",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Maciej",
        "last": "Kazimierowicz",
        "mother": "Barbara",
        "father": "Mariusz Kazimierowicz",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Agata",
        "last": "Klimczak",
        "mother": "Danusia Plesniak",
        "father": "Andrzej Klimczak",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Tomek",
        "last": "Klimczak",
        "mother": "Danusia Plesniak",
        "father": "Andrzej Klimczak",
        "sex": "Male",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Karolina",
        "last": "Szucio",
        "mother": "Urszula Plesniak",
        "father": "Robert Szucio",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Magda",
        "last": "Szucio",
        "mother": "Urszula Plesniak",
        "father": "Robert Szucio",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Barbara",
        "last": "Szucio",
        "mother": "Urszula Plesniak",
        "father": "Robert Szucio",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    },
    {
        "first": "Ania",
        "last": "Plesniak",
        "mother": "Ewa",
        "father": "Zbigniew Plesniak",
        "sex": "Female",
        "spouse": "",
        "birthDate": "",
        "birthLocation": "",
        "birthYear": "",
        "deathYear": ""
    }
];

export default demoData;